trigger:
- master

jobs:
- template: build-job.yml
  parameters:
    name: Linux
    vmImage: 'ubuntu-16.04'
    py: 3.6

- template:  build-job.yml
  parameters:
    name: macOS
    vmImage: 'macOS-10.13'
    py: 3.6

- template:  build-job.yml
  parameters:
    name: Windows
    vmImage: 'vs2017-win2016'
    py: 3.6
    
- template: build-job.yml
  parameters:
    name: Linux
    vmImage: 'ubuntu-16.04'
    py: 2.7

- template:  build-job.yml
  parameters:
    name: macOS
    vmImage: 'macOS-10.13'
    py: 2.7

- template:  build-job.yml
  parameters:
    name: Windows
    vmImage: 'vs2017-win2016'
    py: 2.7