trigger:
- none

jobs:
- template: conda-build.yml
  parameters:
    name: linux_netgen
    vmImage: 'ubuntu-20.04'
    py_maj: 3
    py_min: 12
    location: netgen

- template: conda-build.yml
  parameters:
    name: win_netgen
    vmImage: 'windows-2022'
    py_maj: 3
    py_min: 12
    location: netgen
