trigger:
- master

jobs:
- template: conda-build.yml
  parameters:
    name: Linux-freeimageplus
    vmImage: 'ubuntu-16.04'
    py_maj: 3
    py_min: 6
    location: freeimageplus

- template:  conda-build.yml
  parameters:
    name: macOS-freeimageplus
    vmImage: 'macOS-10.13'
    py_maj: 3
    py_min: 6
    location: freeimageplus

- template:  conda-build.yml
  parameters:
    name: Windows-freeimageplus
    vmImage: 'vs2017-win2016'
    py_maj: 3
    py_min: 6
    location: freeimageplus
    
- template: conda-build.yml
  parameters:
    name: Linux-oce
    vmImage: 'ubuntu-16.04'
    py_maj: 3
    py_min: 6
    location: oce-0.18.3

- template:  conda-build.yml
  parameters:
    name: macOS-oce
    vmImage: 'macOS-10.13'
    py_maj: 3
    py_min: 6
    location: oce-0.18.3

- template:  conda-build.yml
  parameters:
    name: Windows-oce
    vmImage: 'vs2017-win2016'
    py_maj: 3
    py_min: 6
    location: oce-0.18.3

- template: conda-build.yml
  parameters:
    name: Linux-pythonocc36
    vmImage: 'ubuntu-16.04'
    py_maj: 3
    py_min: 6
    location: pythonocc

- template:  conda-build.yml
  parameters:
    name: macOS-pythonocc36
    vmImage: 'macOS-10.13'
    py_maj: 3
    py_min: 6
    location: pythonocc

- template:  conda-build.yml
  parameters:
    name: Windows-pythonocc36
    vmImage: 'vs2017-win2016'
    py_maj: 3
    py_min: 6
    location: pythonocc
    

- template: conda-build.yml
  parameters:
    name: Linux-pythonocc37
    vmImage: 'ubuntu-16.04'
    py_maj: 3
    py_min: 7
    location: pythonocc

- template:  conda-build.yml
  parameters:
    name: macOS-pythonocc37
    vmImage: 'macOS-10.13'
    py_maj: 3
    py_min: 7
    location: pythonocc

- template:  conda-build.yml
  parameters:
    name: Windows-pythonocc37
    vmImage: 'vs2017-win2016'
    py_maj: 3
    py_min: 7
    location: pythonocc
