trigger:
- master

jobs:
- template: build-job.yml
  parameters:
    name: Linux
    vmImage: 'ubuntu-16.04'

- template:  build-job.yml
  parameters:
    name: macOS
    vmImage: 'macOS-10.13'

- template:  build-job.yml
  parameters:
    name: Windows
    vmImage: 'vs2015-win2012r2'