parameters:
  name: 'Build job'  
  vmImage: 'Ubuntu-16.04'
  py: '3.6'

jobs:
- job: ${{ parameters.name }}_oce
  timeoutInMinutes: 240
  
  pool: 
    vmImage: ${{ parameters.vmImage }}
  
  steps:
  - task: CondaEnvironment@1
    inputs:
      createCustomEnvironment: False
      updateConda: False
      packageSpecs: conda-build=3.0.22 conda-verify libarchive python=3 anaconda-client
      installOptions: --channel conda-forge
  
  - script: conda info && conda list
    displayName: 'Conda info'
  
  - script: |
      cd oce-0.18.3
      conda build --token $TOKEN --user cadquery -c conda-forge -c dlr-sc .
      cd ..
    displayName: 'OCE'
    condition: ne( variables['Agent.OS'], 'Windows_NT' )
    env:
      TOKEN: $(anaconda.TOKEN)
      
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64 && set CC=cl && set CXX=cl
      cd oce-0.18.3
      conda build --token %TOKEN% --user cadquery -c conda-forge -c dlr-sc .
      cd ..
    displayName: 'OCE - Windows specific'
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
    env:
      TOKEN: $(anaconda.TOKEN)

- job: ${{ parameters.name }}_pythonocc
  timeoutInMinutes: 240
  
  pool: 
    vmImage: ${{ parameters.vmImage }}
    
  steps:
  - task: CondaEnvironment@1
    inputs:
      createCustomEnvironment: False
      updateConda: False
      packageSpecs: conda-build=3.0.22 conda-verify libarchive python=${{ parameters.py }} anaconda-client
      installOptions: --channel conda-forge
  
  - script: conda info && conda list
    displayName: 'Conda info'  
       
  - script: |
      cd pythonocc
      conda build --token $TOKEN --user cadquery -c cadquery -c conda-forge -c dlr-sc .
      cd ..
    displayName: 'PythonOCC'
    condition: ne( variables['Agent.OS'], 'Windows_NT' )
    env:
      TOKEN: $(anaconda.TOKEN)
      
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64 && set CC=cl && set CXX=cl
      cd pythonocc
      conda build --token %TOKEN% --user cadquery -c cadquery -c conda-forge -c dlr-sc .
      cd ..
    displayName: 'PythonOCC - Windows specific'
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
    env:
      TOKEN: $(anaconda.TOKEN)