parameters:
  name: 'Build job'  
  vmImage: 'Ubuntu-16.04'

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 120
  
  pool: 
    vmImage: ${{ parameters.vmImage }}
  
  steps:
  - task: CondaEnvironment@1
    inputs:
      createCustomEnvironment: False
      updateConda: False
      packageSpecs: conda-build conda-verify python=3 conda=4.3.34
      installOptions: --channel conda-forge
  
  - script: cd oce-0.18.3 && conda build -c conda-forge -c dlr-sc . && cd ..
    displayName: 'OCE'
          
  - bash: cd pythonocc && conda build -c conda-forge -c dlr-sc . && cd ..
    displayName: 'PythonOCC'