steps:

# install conda for mac
- bash: brew install miniforge && ls /usr/local/Caskroom/miniforge/base && ls /usr/local/Caskroom/miniforge/
  displayName: 'MacOS install miniforge'
  condition: eq( variables['Agent.OS'], 'Darwin' )

#activate conda
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  condition: ne( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Add conda to PATH'
- powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Add conda to PATH - Windows'

# install mamba
- bash: |
      conda config --set anaconda_upload yes --set always_yes yes --set solver libmamba && \
      conda config --add channels conda-forge && \
      conda install -c conda-forge -q mamba=1.5 conda-devenv libsolv conda-libmamba-solver && \
      mamba info && \
      mamba list
  displayName: 'Install mamba, boa; report config and info'
