steps:

# install conda for mac
- bash: brew install miniforge && ls /usr/local/Caskroom/miniforge/base/bin
  displayName: 'MacOS install miniforge'
  condition: eq( variables['Agent.OS'], 'Darwin' )

#activate conda
- bash: echo "##vso[task.prependpath]/usr/local/Caskroom/miniforge/base/bin"
  condition: eq( variables['Agent.OS'], 'Darwin' )
  displayName: 'Add conda to PATH - OSX'

- bash: echo "##vso[task.prependpath]$CONDA/bin"
  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: 'Add conda to PATH - Linux'

- powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Add conda to PATH - Windows'

- powershell: Write-Host "##vso[task.prependpath]$env:CONDA\condabin"
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Add condabin to PATH - Windows'

# install mamba
- bash: |
      conda config --set anaconda_upload yes --set always_yes yes --set solver libmamba && \
      conda config --add channels conda-forge && \
      conda install -c conda-forge -q mamba micromamba conda-devenv libsolv conda-libmamba-solver && \
      mamba info && \
      mamba list
  displayName: 'Install mamba, boa; report config and info'
