parameters:
  name: 'Conda build job'
  vmImage: 'Ubuntu-16.04'
  py_maj: '3'
  py_min: '6'
  location: 'conda'
  conda_bld: '3.16.3'
  conda: '22.9.0'

jobs:
- job: ${{ parameters.name }}_${{ parameters.py_maj }}_${{ parameters.py_min }}
  timeoutInMinutes: 360
  
  pool:
    vmImage: ${{ parameters.vmImage }}
    
  steps: 
  
  #activate conda
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    condition: ne( variables['Agent.OS'], 'Windows_NT' )
    displayName: 'Add conda to PATH'
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
    displayName: 'Add conda to PATH - Windows'
  
  # this step is needed for OCC to find fonts
  - bash: |
      sudo apt-get -q -y install gsfonts xfonts-utils && \
      sudo mkfontscale /usr/share/fonts/type1/gsfonts/ && \
      sudo mkfontdir /usr/share/fonts/type1/gsfonts/
    condition: eq( variables['Agent.OS'], 'Linux' )
    displayName: 'Help OCC find fonts'
        
  # Ubunut install opengl items
  - ${{ if contains(parameters.vmImage, 'Ubuntu') }}:
    - bash: |
        sudo apt-get update && \
        sudo apt-get -q -y install libglu1-mesa-dev freeglut3-dev mesa-common-dev
      displayName: 'Install OpenGL headers'
  
  # macOS ownership workaround
  - ${{ if contains(parameters.vmImage, 'macOS') }}:
    - bash: |
        sudo chown -R $USER $CONDA && \
        curl -o MacOSX10.9.sdk.tar.xz -L https://github.com/phracker/MacOSX-SDKs/releases/download/10.13/MacOSX10.9.sdk.tar.xz && \
        tar xf MacOSX10.9.sdk.tar.xz && \
        sudo mv -v MacOSX10.9.sdk /opt/ 
      displayName: 'MacOS ownership workaround + 10.9 SDK installation'    	
      
  - bash: |
        conda config --set anaconda_upload yes --set always_yes yes && \
        conda install -q conda-forge::mamba=1 conda-forge::boa && \
        mamba info && \
        mamba list
    displayName: 'Install mamba, boa; report config and info'
      
  - bash: mamba create --yes --quiet --name build_env -c conda-forge conda-build=${{ parameters.conda_bld }} conda-verify libarchive python=3.7 anaconda-client
    displayName: Create Anaconda environment
    
  - bash: |
      source activate build_env && \
      cd ${{ parameters.location }} && \
      mamba run -n build_env conda mambabuild -c conda-forge -c cadquery --output-folder . . && \
      full_path=$(mamba run -n build_env conda build --output -c conda-forge -c cadquery --output-folder . . ) && \
      echo $full_path && \
      base_name=$(basename $full_path) && \
      split_name=($(IFS=-; tmp=($base_name); echo ${tmp[@]})) && \
      package_name=${split_name[@]: 0 : ${#split_name[@]} - 2} && \
      package_name=${package_name/ /-} && \
      version_name=${split_name[-2]} && \
      echo "Removing $base_name" && \
      mamba run -n build_env anaconda -v -t $TOKEN remove --force "cadquery/$package_name/$version_name"  && \
      echo "Uploading $full_path" && \
      mamba run -n build_env anaconda -v -t $TOKEN upload -u cadquery --force $full_path && \
      cd ..
    displayName: 'Run conda build'
    failOnStderr: false
    condition: ne(variables['Build.Reason'], 'PullRequest')
    env:
      PYTHON_VERSION: ${{ parameters.py_maj }}.${{ parameters.py_min }}
      PACKAGE_VERSION: $(Build.SourceBranchName)
      TOKEN: $(anaconda.TOKEN)
    
  - bash: |
      cd ${{ parameters.location }} && \
      mamba run -n build_env conda mambabuild -c conda-forge -c cadquery . && \
      cd ..
    displayName: 'Run conda build without upload'
    failOnStderr: false
    condition: eq(variables['Build.Reason'], 'PullRequest')
    env:
      PYTHON_VERSION: ${{ parameters.py_maj }}.${{ parameters.py_min }}
      PACKAGE_VERSION: $(Build.SourceBranchName)
      TOKEN: $(anaconda.TOKEN)
