steps:

- bash: echo ${{ variables.Agent.OS }}
  displayName: 'Current OS value'

#activate conda
- ${{ if or(contains(variables.Agent.OS, 'Darwin'),contains(variables.Agent.OS, 'Linux')) }}:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: 'Add conda to PATH'
- ${{ if contains(variables.Agent.OS, 'Windows') }}:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: 'Add conda to PATH'

# macOS ownership workaround
- ${{ if contains(variables.Agent.OS, 'Darwin') }}:
  - bash: sudo chown -R $USER $CONDA
    displayName: 'MacOS ownership workaround'

- bash: |
      conda config --set anaconda_upload yes --set always_yes yes && \
      conda info && \
      conda list
  displayName: 'Conda config and info'

