steps:

#activate conda
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  condition: ne( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Add conda to PATH'
- powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Add conda to PATH - Windows'

# macOS ownership workaround
- bash: sudo chown -R $USER $CONDA
  displayName: 'MacOS ownership workaround'
  condition: eq( variables['Agent.OS'], 'Darwin' )

# install mamba
- bash: |
      conda config --set anaconda_upload yes --set always_yes yes && \
      conda install -q conda-forge::mamba=1.4 conda-forge::boa conda-forge::libarchive conda-forge::conda-devenv && \
      mamba info && \
      mamba list
  displayName: 'Install mamba, boa; report config and info'
