steps:

#donwload and install conda
- bash: |
    curl -fsSLo Miniforge.exe https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Windows-x86_64.exe && \
    ./Miniforge.exe /InstallationType=JustMe /RegisterPython=0 /S /D=_miniconda
  condition: eq( variables['Agent.OS'], 'Windows_NT' )

- bash: |
     curl -sL https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh > miniconda.sh && \
     bash miniconda.sh -b -p _miniconda
    
#activate conda
- bash: echo "##vso[task.prependpath]_miniconda/bin"
  condition: ne( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Add conda to PATH'
- powershell: Write-Host "##vso[task.prependpath]_miniconda\Scripts"
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'Add conda to PATH - Windows'

# macOS ownership workaround
- bash: sudo chown -R $USER $CONDA
  displayName: 'MacOS ownership workaround'
  condition: eq( variables['Agent.OS'], 'Darwin' )

# install mamba
- bash: |
      conda config --set anaconda_upload yes --set always_yes yes --set solver libmamba && \
      mamba install -c conda-forge conda-devenv libsolv conda-libmamba-solver && \
      mamba info && \
      mamba list
  displayName: 'Install mamba, boa; report config and info'
