parameters:
  name: 'Constructor_installer_build'
  vmImage: 'ubuntu-latest'

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 360
  
  pool:
    vmImage: ${{ parameters.vmImage }}
    
  steps: 
  
  - template: conda-enable.yml
  
  - bash: mamba install -c conda-forge constructor conda-libmamba-solver
    displayName: 'Install constructor'

  - bash: mkdir out && cd out && constructor ../conda
    env:
      CONDA_SOLVER: libmamba
    displayName: 'Build'

  - publish:  out
    artifact: installer_${{ parameters.vmImage }}
  
