parameters:
  name: 'Constructor_installer_build'
  vmImage: 'ubuntu-latest'

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 360
  
  pool:
    vmImage: ${{ parameters.vmImage }}
    
  steps: 
  
  - template: conda-enable.yml
  - bash: mamba install conda-forge::constructor
  - bash: mkdir out && cd out && constructor ../conda
  - publish:  out
    artifact: installer_${{ parameters.vmImage }}
  
